### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by JasperGeurtz** [JasperGeurtz/JBWAPI#1]
### Unordered roadmap for v1.0
- [x] Add all events to gameloop
- [x] Implement Player
- [x] Implement Unit
- [x] Implement Game
- [x] Implement Force
- [x] Implement Region
- [x] Implement Bullet
- [x] Implement UnitCommand static methods
- [x] Implement Tile/Walk/Position
- [x] Operations add, substract, multiply for Tile/Walk/Positions
- [x] Implement PlayerType
- [x] Implement Race
- [x] Implement TechType
- [x] Implement UnitType
- [x] Implement UpgradeType
- [x] Implement WeaponType
- [x] Implement Color
- [x] Implement draws
- [x] Resolve all remaining TODO's  in the code

**Comment by JasperGeurtz** [comment]
Full interface now finished minus eventual bugs/performance optimisations
